spring:
 jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   show-sql: true
   hibernate:
     ddl-auto: update
   open-in-view: false
 datasource:
  url: jdbc:mysql://localhost:3308/test_db?createDatabaseIfNotExist=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password